### ISSUE TITLE
Use Docker support in Travis CI

### ISSUE THREAD

**Issue by aspino** [EASOL/easol-docker#3]
Since the project is using Travis CI for unit testing, we could leverage its Docker support and use the easol-docker image as the main system for running the tests.

**Comment by jasonhoekstra** [comment]
@aspino Sounds good and let's work together this week to push to Travis.  Now that the project is open-source in public, we can use travis-ci.org instead of previously using travis-ci.com which will be good to use the free service

**Comment by aspino** [comment]
@jasonhoekstra @edgarf I think Travis integration is finally configured and working. Right now the builds are failing but I guess it's because the tests themselves are not yet ready. Once they run fine the travis builds should start working.

Anyway, I've created a pull request: https://github.com/EASOL/easol/pull/219, so feel free to review/merge it whenever you want Travis to start using `easol-docker` to run the `easol` tests.
